
import { GoogleGenAI, Type, Modality } from '@google/genai';
import { AnalysisResult, ImpactData } from '../types';
import { furnitureData, CO2_KM_DRIVEN_FACTOR, UPCYCLING_COSTS } from './data';

// On initialise le client. Si la clé est vide, l'erreur surviendra lors de l'appel generateContent,
// ce qui permet à l'UI de charger correctement (Header, etc.) au lieu d'avoir un écran noir.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

const furnitureTypes = Object.keys(furnitureData);
const materials = ['wood', 'metal', 'particle board', 'plastic', 'fabric'];

function calculateImpact(type: string, material: string): ImpactData {
  const key = `${material} ${type}`.toLowerCase();
  const data = furnitureData[key] || furnitureData['wooden chair']; // Fallback to a default

  const co2Saved = data.co2_new - 5; // Assuming a small constant CO2 cost for upcycling
  const communityCostAvoided = data.weight_kg * data.disposal_cost_per_kg;
  const valueCreated = data.new_price - UPCYCLING_COSTS;

  return { co2Saved, communityCostAvoided, valueCreated };
}

export async function analyzeFurnitureImage(base64Data: string): Promise<AnalysisResult> {
  if (!process.env.API_KEY) {
      console.error("API Key manquante dans process.env.API_KEY");
      throw new Error("La clé API n'est pas configurée.");
  }

  const imagePart = {
    inlineData: {
      mimeType: 'image/jpeg',
      data: base64Data,
    },
  };
  
  const textPart = {
      text: `Analyze this image of a piece of furniture. Identify the main furniture type and its primary material from the provided lists.
      
      Valid furniture types: ${furnitureTypes.join(', ')}
      Valid materials: ${materials.join(', ')}
      
      Respond ONLY with a JSON object matching the specified schema. If you cannot determine the type or material, use "unknown".`
  };

  try {
      const response = await ai.models.generateContent({
          model: 'gemini-2.5-flash',
          contents: { parts: [imagePart, textPart] },
          config: {
              responseMimeType: "application/json",
              responseSchema: {
                  type: Type.OBJECT,
                  properties: {
                      furnitureType: { type: Type.STRING, enum: furnitureTypes, description: "The type of furniture." },
                      furnitureMaterial: { type: Type.STRING, enum: materials, description: "The primary material of the furniture." },
                  },
                  required: ['furnitureType', 'furnitureMaterial']
              },
          },
      });

      let jsonResponseText = response.text.trim();
      
      // Extraction robuste du JSON : on cherche la première accolade ouvrante et la dernière fermante
      // cela permet d'ignorer le texte ou le markdown (```json) qui pourrait entourer la réponse.
      const firstBrace = jsonResponseText.indexOf('{');
      const lastBrace = jsonResponseText.lastIndexOf('}');

      if (firstBrace !== -1 && lastBrace !== -1) {
          jsonResponseText = jsonResponseText.substring(firstBrace, lastBrace + 1);
      }

      const result = JSON.parse(jsonResponseText);
      
      const { furnitureType, furnitureMaterial } = result;

      if (furnitureType === 'unknown' || furnitureMaterial === 'unknown') {
        throw new Error('Could not identify furniture type or material.');
      }

      const impact = calculateImpact(furnitureType, furnitureMaterial);

      return {
        furnitureType,
        furnitureMaterial,
        impact,
      };
  } catch (error) {
      console.error("Erreur lors de l'analyse Gemini:", error);
      throw error;
  }
}

export async function editImage(base64Data: string, mimeType: string, prompt: string): Promise<string> {
    if (!process.env.API_KEY) {
        throw new Error("La clé API n'est pas configurée.");
    }

    const imagePart = {
        inlineData: {
          data: base64Data,
          mimeType: mimeType,
        },
    };
    const textPart = { text: prompt };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts: [imagePart, textPart] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }

    throw new Error('No image was generated by the API.');
}
